### PR TITLE
Instructions for running workflow on OSG

### PR DESCRIPTION
**Pull request by duncan-brown**
Workflow generation script and instructions for running on OSG.

### CODE REVIEW

**Comment by duncan-brown** [comment]
@ahnitz please can you read through for any issues, but hold off merging for the moment. I'm seeing occasional issues where jobs are put on hold when they exceed the requested memory, and I want to come up with a ClassAd to handle this automatically.

```
1050981.0   dbrown         11/7  23:48 Job in status 2 put on hold by SYSTEM_PERIODIC_HOLD due to memory usage 3000000.
1051049.0   dbrown         11/7  23:48 Job in status 2 put on hold by SYSTEM_PERIODIC_HOLD due to memory usage 3000000.
1051320.0   dbrown         11/7  23:48 Job in status 2 put on hold by SYSTEM_PERIODIC_HOLD due to memory usage 3250000.
```

```
(pycbc-opengw) [dbrown@login03 o1-analysis-test-v1_13_0-LOSC_16_V1-main_ID0000001]$ condor_q -long 1050981.0 | grep -i memory
AutoClusterAttrs = "ConcurrencyLimits,NiceUser,Rank,Requirements,DESIRED_Resources,ITB_Factory,ITB_Sites,JobUniverse,LastCheckpointPlatform,MachineLastMatchTime,NumCkpts,Owner,_condor_RequestCpus,_condor_RequestDisk,_condor_RequestMemory,CVMFS_stash_osgstorage_org_REVISION,D_PID,DESIRED_Sites,DynamicSlot,PartitionableSlot,ProjectName,RequestCpus,RequestDisk,RequestGPUs,RequestMemory,RequiresBigMem,RequiresLongWalltime,RequiresWholeMachine,RunOnSubmitNode,SleepSlot,Slot10_RemoteOwner,Slot1_RemoteOwner,Slot1_SelfMonitorAge,Slot1_TotalTimeClaimedBusy,Slot1_TotalTimeUnclaimedIdle,Slot2_RemoteOwner,Slot3_RemoteOwner,Slot4_RemoteOwner,Slot5_RemoteOwner,Slot6_RemoteOwner,Slot7_RemoteOwner,Slot8_RemoteOwner,Slot9_RemoteOwner,SUBMITTER_stash_osgstorage_org_REVISION,undeined,User,WantsStashCvmfs,x509userproxysubject,_condor_RequestGPUs,CONDOR,SLATE,Unknown,Unknown00"
InitialRequestMemory = 1920
LastHoldReason = "Job in status 2 put on hold by SYSTEM_PERIODIC_HOLD due to memory usage 3000000."
MemoryProvisioned = 2560
MemoryUsage = ((ResidentSetSize + 1023) / 1024)
RequestMemory = 3500
Requirements = (((HAS_CVMFS_oasis_opensciencegrid_org =?= true) && (HAS_CVMFS_gwosc_osgstorage_org =?= true) && (HAS_CVMFS_gwosc_osgstorage_org =?= true) && (HAS_SINGULARITY =?= true) && (OSG_GLIDEIN_VERSION >= 346))) && (TARGET.Arch == "X86_64") && (TARGET.OpSys == "LINUX") && (TARGET.Disk >= RequestDisk) && (TARGET.Memory >= RequestMemory) && (TARGET.HasFileTransfer)
```

```
(pycbc-opengw) [dbrown@login03 o1-analysis-test-v1_13_0-LOSC_16_V1-main_ID0000001]$ condor_q -long 1050981.0 | grep -i status
EnteredCurrentStatus = 1541656118
ExitStatus = 0
JobStatus = 1
LastHoldReason = "Job in status 2 put on hold by SYSTEM_PERIODIC_HOLD due to memory usage 3000000."
LastJobStatus = 5
PeriodicHold = (JobStatus == 2) && ((CurrentTime - EnteredCurrentStatus) > (2 * 86400))
PeriodicRelease = ((HoldReasonCode =?= 34) || (HoldReasonCode =?= 26)) || ((JobStatus == 5) && (HoldReasonCode == 3) && (NumJobStarts < 5) && ((CurrentTime - EnteredCurrentStatus) > (300)))
```

```
LastHoldReason = "Job in status 2 put on hold by SYSTEM_PERIODIC_HOLD due to memory usage 2250000."
LastHoldReasonCode = 26
LastHoldReasonSubCode = 0
```

**Comment by duncan-brown** [comment]
Test workflow runs fine in the `vanilla` environment (i.e. for Atlas or SUGWG nodes)

https://sugwg-osg.phy.syr.edu/pegasus/u/dbrown/r/614/w?wf_uuid=ca27827a-a901-4311-ad31-7a9a724014fd

**Comment by duncan-brown** [comment]
Large workflows are slow to finish up due to the limit on the number of stage out jobs: https://pegasus.isi.edu/documentation/job_throttling.php

**Comment by duncan-brown** [comment]
Test workflow runs fine on OrangeGrid

https://sugwg-scitokens.phy.syr.edu/pegasus/u/dbrown/r/621/w?wf_uuid=97dd61b0-afda-42e0-89b2-804c7a9a3d3c

**Comment by duncan-brown** [comment]
Until https://jira.isi.edu/browse/PM-1329 is fixed, I need to disable integrity checking.

**Review by Rebecca333 — APPROVED** [review]
The test-workflow worked.

**Pull request merged**
